# Generated by Django 2.2.3 on 2019-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_password_change',
            field=models.DateTimeField(blank=True, default=None, help_text='Datetime when user changed the password for the last time.', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('USER', 'User')], default='USER', help_text="User's role in the system.", max_length=20),
        ),
    ]
