FROM centos:latest

ARG bsp_username="app_user"
RUN useradd $bsp_username --home-dir /opt/app
WORKDIR /opt/app

ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN yum update -y && yum install python3 -y

COPY requirements.txt /opt/app

RUN yum install gettext mc vim -y
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt --no-cache-dir

USER $bsp_username
