FROM python:3.6-slim

COPY config/project /etc/logrotate.d

WORKDIR /app

ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


COPY requirements.txt /app
RUN pip install -r requirements.txt --no-cache-dir
